import type { CommandDef } from 'citty'

export const commands = {
  'init': () => import('./init').then(m => m.default as CommandDef),
  'info': () => import('./info').then(m => m.default as CommandDef),
  'format': () => import('./format').then(m => m.default as CommandDef),
  'split': () => import('./split').then(m => m.default as CommandDef),
  'import': () => import('./import').then(m => m.default as CommandDef),
  'export': () => import('./export').then(m => m.default as CommandDef),
  'extract': () => import('./extract').then(m => m.default as CommandDef),
  'sync': () => import('./sync').then(m => m.default as CommandDef),
  'sync-remote': () => import('./sync-remote').then(m => m.default as CommandDef),
  'validate': () => import('./validate').then(m => m.default as CommandDef),
  'stats': () => import('./stats').then(m => m.default as CommandDef),
  'clean': () => import('./clean').then(m => m.default as CommandDef),
  'translate': () => import('./translate').then(m => m.default as CommandDef),
  'export-csv': () => import('./export-csv').then(m => m.default as CommandDef),
  'import-csv': () => import('./import-csv').then(m => m.default as CommandDef),
  'diff': () => import('./diff').then(m => m.default as CommandDef),
  'check-duplicates': () => import('./check-duplicates').then(m => m.default as CommandDef),
  'replace-values': () => import('./replace-values').then(m => m.default as CommandDef),
  'optimize': () => import('./optimize').then(m => m.default as CommandDef),
  'text-to-i18n': () => import('./text-to-i18n').then(m => m.default as CommandDef),
  'search': () => import('./search').then(m => m.default as CommandDef),
  'rename': () => import('./rename').then(m => m.default as CommandDef),
  'pseudo': () => import('./pseudo').then(m => m.default as CommandDef),
  'estimate': () => import('./estimate').then(m => m.default as CommandDef),
  'glossary': () => import('./glossary').then(m => m.default as CommandDef),
  'backup': () => import('./backup').then(m => m.default as CommandDef),
  'restore': () => import('./restore').then(m => m.default as CommandDef),
  'lint': () => import('./lint').then(m => m.default as CommandDef),
} as const
